### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Riikuma** [Riikuma/furima-35534#9]
追記：下のコメントをご確認ください。

# フリマアプリのURL
https://furima-35534.herokuapp.com/

# Basic認証のIDとパスワード
ユーザー名　admin
パスワード　2222

# 出品者用のメールアドレスとパスワード
（ユーザー名　フリマちゃん）
メールアドレス　aaa@com
パスワード　aaa123

# 購入者用のメールアドレスとパスワード
（ユーザー名　やまさん）
メールアドレス　bbb@com
パスワード　bbb123

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/119936646-7ad1d800-bfc4-11eb-88da-fc3db123780a.png)

**Comment by Riikuma** [comment]
LGTMありがとうございます。
ただ頂いた文章の後半が恐らくプロトスペースのものだと思うので確認なのですが、次の指示としては追加実装やオリジナルアプリを私自身が進んで実装し、slackの方には以降特に案内もないということでよろしいでしょうか。
ご確認よろしくお願いいたします。

**Comment by mo1015** [comment]
> ただ頂いた文章の後半が恐らくプロトスペースのものだと思うので確認なのですが、次の指示としては追加実装やオリジナルアプリを私自身が進んで実装し、slackの方には以降特に案内もないということでよろしいでしょうか。

大変失礼いたしました。おっしゃる通りこちらの文章はプロトスペースのものでございます。
混乱させてしまって申し訳ございません。
以降別途連絡はございませんのでご安心ください！

**Comment by Riikuma** [comment]
承知いたしました。ありがとうございました！
